services:
  paraphraser-api:
    build: .
    container_name: paraphraser-app
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    volumes:
      - .:/app
    restart: unless-stopped
